name: 'Commit Message Check'

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-for-cc:
    runs-on: ubuntu-latest
    steps:
      - name: check-for-cc
        id: check-for-cc
        uses: agenthunt/conventional-commit-checker-action@master
        with:
          pr-title-regex: '^(feat|refactor|fix|test|build|ci|docs)(\((adaptors|app|auth|batch|http|messaging|metadata|model|opds|plugins|reader|release|repositories|rest|services|state|webui)\))?: (.+) (\[\#[\d]+\])'
